etcd:
  image: microbox/etcd:latest
  command: -name etcd-node1 --addr 172.17.42.1:4001
  ports:
  - 4001:4001
  - 7001:7001

registrator:
  command: -internal etcd://etcd:4001/services
  image: gliderlabs/registrator:latest
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  links:
  -  etcd:etcd

confd:
  build: ./nginx-confd-etcd
  links:
  -  etcd:etcd
  volumes:
  - ./nginx-confd-etcd/confd/nginx.tmpl:/etc/confd/templates/nginx.tmpl
  environment:
    - ETCD=172.17.42.1:4001
  ports:
  - 80:80
